// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AnnouncementBarDocumentDataSlicesSlice = AnnouncementBarSlice;

/**
 * Content for Announcement Bar documents
 */
interface AnnouncementBarDocumentData {
  /**
   * Slice Zone field in *Announcement Bar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AnnouncementBarDocumentDataSlicesSlice>;
}

/**
 * Announcement Bar document from Prismic
 *
 * - **API ID**: `announcement_bar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AnnouncementBarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AnnouncementBarDocumentData>,
    "announcement_bar",
    Lang
  >;

type ArticleDocumentDataSlicesSlice =
  | ArticleImageBlockSlice
  | ArticleRichTextSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Publication date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publication_date: prismic.DateField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

export type AllDocumentTypes = AnnouncementBarDocument | ArticleDocument;

/**
 * Primary content in *AnnouncementBar → Primary*
 */
export interface AnnouncementBarSliceDefaultPrimary {
  /**
   * Title field in *AnnouncementBar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Button field in *AnnouncementBar → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * Link field in *AnnouncementBar → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Enable field in *AnnouncementBar → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: announcement_bar.primary.enable
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  enable: prismic.BooleanField;
}

/**
 * Default variation for AnnouncementBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnnouncementBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AnnouncementBar*
 */
type AnnouncementBarSliceVariation = AnnouncementBarSliceDefault;

/**
 * AnnouncementBar Shared Slice
 *
 * - **API ID**: `announcement_bar`
 * - **Description**: AnnouncementBar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementBarSlice = prismic.SharedSlice<
  "announcement_bar",
  AnnouncementBarSliceVariation
>;

/**
 * Primary content in *ArticleImageBlock → Primary*
 */
export interface ArticleImageBlockSliceDefaultPrimary {
  /**
   * Image field in *ArticleImageBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_image_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ArticleImageBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_image_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ArticleImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleImageBlock*
 */
type ArticleImageBlockSliceVariation = ArticleImageBlockSliceDefault;

/**
 * ArticleImageBlock Shared Slice
 *
 * - **API ID**: `article_image_block`
 * - **Description**: ArticleImageBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleImageBlockSlice = prismic.SharedSlice<
  "article_image_block",
  ArticleImageBlockSliceVariation
>;

/**
 * Primary content in *ArticleRichText → Primary*
 */
export interface ArticleRichTextSliceDefaultPrimary {
  /**
   * Text field in *ArticleRichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_rich_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ArticleRichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleRichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleRichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleRichText*
 */
type ArticleRichTextSliceVariation = ArticleRichTextSliceDefault;

/**
 * ArticleRichText Shared Slice
 *
 * - **API ID**: `article_rich_text`
 * - **Description**: ArticleRichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleRichTextSlice = prismic.SharedSlice<
  "article_rich_text",
  ArticleRichTextSliceVariation
>;

/**
 * Primary content in *MarketingBanner → Primary*
 */
export interface MarketingBannerSliceDefaultPrimary {
  /**
   * Image field in *MarketingBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing_banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *MarketingBanner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing_banner.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Button field in *MarketingBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing_banner.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * Start at field in *MarketingBanner → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing_banner.primary.start_at
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_at: prismic.DateField;

  /**
   * End at field in *MarketingBanner → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: marketing_banner.primary.end_at
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_at: prismic.DateField;
}

/**
 * Default variation for MarketingBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarketingBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarketingBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MarketingBanner*
 */
type MarketingBannerSliceVariation = MarketingBannerSliceDefault;

/**
 * MarketingBanner Shared Slice
 *
 * - **API ID**: `marketing_banner`
 * - **Description**: MarketingBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarketingBannerSlice = prismic.SharedSlice<
  "marketing_banner",
  MarketingBannerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AnnouncementBarDocument,
      AnnouncementBarDocumentData,
      AnnouncementBarDocumentDataSlicesSlice,
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnnouncementBarSlice,
      AnnouncementBarSliceVariation,
      AnnouncementBarSliceDefault,
      ArticleImageBlockSlice,
      ArticleImageBlockSliceVariation,
      ArticleImageBlockSliceDefault,
      ArticleRichTextSlice,
      ArticleRichTextSliceVariation,
      ArticleRichTextSliceDefault,
      MarketingBannerSlice,
      MarketingBannerSliceVariation,
      MarketingBannerSliceDefault,
    };
  }
}
