// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  announcement_bar: dynamic(() => import("./AnnouncementBar")),
  article_image_block: dynamic(() => import("./ArticleImageBlock")),
  article_rich_text: dynamic(() => import("./ArticleRichText")),
  marketing_banner: dynamic(() => import("./MarketingBanner")),
};
