import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { createClient } from "@/prismicio";
import { SliceZone } from "@prismicio/react";
import { components } from "@/slices";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = createClient();
  const announcementBar = await client.getSingle("announcement_bar");

  return (
    <html lang="en">
      <body className={inter.className}>
        <SliceZone
          slices={announcementBar.data.slices}
          components={components}
          key={announcementBar.uid}
        />
        <div>{children}</div>
      </body>
      <Script src="https://static.cdn.prismic.io/prismic.js?new=true&repo=nextjs-pro" />
    </html>
  );
}
